# Renseigner dans ce fichier les infos confidentielles de connexion à des APIs ou applications tierces : base de donnée, server d'email, server d'autentification ...
# Ce fichier ne doit pas faire partie du dépot Git, il est à remettre au Campus Manager en fin de projet

